name: GitHub Actions EPROD Training Demo

on: 
  push:
    branches: [ main ]
    paths-ignore: [.github/**]
  pull_request:
    branches: [ main ]
  schedule: 
    - cron: '15 6 * * 0'
  workflow_dispatch:

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo " The Job was triggers by an event: ${{ github.event_name }}"
          echo " The names of the branch is ${{ github.ref }} and your repository is ${{ github.repository }}."

      - uses: actions/checkout@v4

      - name: List files that exists in this repo
        run: |
          echo "The repository ${{ github.repository }} contains the following files $ {{ github.workspace }} "
