name: CI Process for docker

on:
  push:
    branches: [ main ]
    paths: [ docker-action ]
  workflow_dispatch:

jobs:
  test-action:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run my container action
        id: hello-action
        uses: ./docker-action
        with:
          who-to-greet: '@ellisd4'

      - name: Get the output time in container
        run: echo "The time twas ${{ steps.hello-action.outputs.time }} when the action said hello!" 
